# docker-compose.yml (Versión Final y Corregida)


services:
  # Servicio de la Base de Datos
  db:
    image: postgres:13-alpine
    container_name: muebles_marcelo_db
    restart: unless-stopped
    command: postgres -c password_encryption=md5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      # ¡CORREGIDO! Asegúrate de que tu carpeta de scripts se llame 'db_scripts'
      - ./postgres_data:/var/lib/postgresql/data
      - ./database_sql:/docker-entrypoint-initdb.d
    networks:
      - muebles-marcelo-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de la API de NestJS
  api:
    build:
      # context: ./muebles-marcelo-api
      dockerfile: Dockerfile.dev
    ### linea comentada que sirve para crear una imagen de la API ###
    # image: tu_usuario_dockerhub/pyme-api:latest
    container_name: muebles_marcelo_api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_NAME}
    networks:
      - muebles-marcelo-net
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

networks:
  muebles-marcelo-net:
    driver: bridge
